groups:
- name: alert.rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: "critical"
    annotations:
      summary: "Endpoint {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."

  - alert: Volume Used Percentage > 90%
    expr: volume_size_used_percent > 90
    for: 1m
    labels:
      severity: "critical"
    annotations:
      summary: "Volume {{ $labels.instance }} 90% used"
      description: "{{ $labels.instance }} of job {{ $labels.job }}'s volume is > 90 used"
