# promeheus.yml
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['harvest_prometheus:9090']
#- job_name: 'node-exporter'
#  static_configs:
#  - targets: ['node-exporter:9100']
- job_name: 'harvest'
  static_configs:
  - targets: ['harvest_ansible-src:25000']
  - targets: ['harvest_ansible_cluster:25001']
