# promeheus.yml
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
rule_files:
  - alert.rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'harvest_prometheus_alertmanager:9093'
scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['harvest_prometheus:9090']
#- job_name: 'node-exporter'
#  static_configs:
#  - targets: ['node-exporter:9100']
- job_name: 'harvest'
  static_configs:
